# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-11 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_author',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
