# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-28 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0004_auto_20160518_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='blog_keywords',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
